<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_Create_Store_With_Data_File</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>529dea15-84dc-4294-843d-10a34f73dc30</testSuiteGuid>
   <testCaseLink>
      <guid>85f73e45-6e29-41ba-b09e-2d2048d524ad</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lession2/TC_Create_Store</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>fc7cf31f-0a68-4408-873a-4bc32efdf31c</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/5store</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0290e438-cb84-417e-ad20-062c6f9c84db</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2e1c94f3-dcde-4219-8d55-1bb2dd2fde88</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fac96156-9f45-4403-9c5d-26ecedc68c9b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae6120c4-9745-4378-ad84-2ef6f976ad05</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5eb42219-8a59-4ec8-b62a-be20b35a8cdd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>76222791-b3c6-4ac6-8063-d917d5db217c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f41aea8e-efb6-448e-819d-71f9a3bbc49e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b4f7f54d-2789-4f97-90d7-d2e9ce4ada87</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>fc7cf31f-0a68-4408-873a-4bc32efdf31c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>dataStoreName</value>
         <variableId>cac8ca50-17ab-4832-8ace-36405b245bd2</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
